# Generated by Django 4.2 on 2023-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_mail_alter_user_password_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('message', models.TextField(max_length=128, verbose_name='Отзыв')),
                ('date', models.CharField(blank=True, max_length=11, verbose_name='Дата отправки')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=128, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя пользователя'),
        ),
    ]
